app_RRHH/urls.py
from django.urls import path
from app_RRHH import views

app_name='app_RRHH'

urlpatterns = [
    path('', views.HomeView.as_view(), name='rrhhhome'),
    path('<int:pk>/',views.DetalleView.as_view(), name='detalle'),
    path('create', views.CreatePersona.as_view(), name='create'),
    path('delete/<int:pk>/', views.DeleteViews.as_view(), name='delete'),
    path('editar/<int:pk>/', views.EditarView.as_view(), name='editar'),
    path('edit/<int:id>/', views.EditView.as_view(), name='edit'),
]

sap/urls.py
from django.contrib import admin
from django.urls import path, include
from sap import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rrhh/', include('app_RRHH.urls', namespace='app_RRHH')),
    path('', views.HomeView.as_view(), name='home')
]

app_RRHH/models.py
from datetime import datetime, date
from django.db import models

# Create your models here.
class PuestoLaboral(models.Model):
    PROCESO_CHOICES = (
        ('P','Produccion'),
        ('C','Calidad'),
        ('R','RRHH'),
        ('A','Administracion'),
        ('E','Expedicion'),
        ('T','Tecnica'),
        ('x','Postulante'),
    )
    area_laboral = models.CharField(max_length=1, choices=PROCESO_CHOICES)
    puesto_laboral = models.CharField(max_length=30)
    descrpcion = models.TextField()

    def __str__(self):
        return f'{self.area_laboral} - Puesto laboral: {self.puesto_laboral}'

class Empleado(models.Model):
    SEXO_CHOICES = (
        ('M','Masculino'),
        ('F','Femenino'),
    )
    nombre = models.CharField(max_length=15)
    apellido = models.CharField(max_length=15)
    dni = models.CharField(max_length=8, verbose_name='DNI')
    sexo = models.CharField(max_length=1, choices=SEXO_CHOICES)
    fec_nac = models.DateField(verbose_name='fecha nacimiento')
    puesto = models.ForeignKey(PuestoLaboral, on_delete=models.CASCADE, null=False, blank=True)
    fec_ing = models.DateField(verbose_name='fecha ingreso', null=False, blank=True)
    activo = models.BooleanField(default=False, verbose_name='Empleado activo?')
    
    def __str__(self):
        if self.activo:
            return f'Empleado {self.nombre} {self.apellido} - Area: {self.puesto.puesto_laboral}'
        else:
            return f'Persona {self.nombre} {self.apellido} - No Activo(a)'

    def edad_persona(self):
        hoy = date.today()
        edad = date.today().year - self.fec_nac.year
        if (hoy.month, hoy.day) < (self.fec_nac.month, self.fec_nac.day):
            return edad - 1
        else:
            return edad

app_RRHH/forms.py
from dataclasses import fields
from django.forms import forms, ModelForm
from app_RRHH import models


class Contact(forms.Form):
    pass


class EditarF(ModelForm):
    class Meta:
        model = models.Empleado
        fields = '__all__'

app_RRHH/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views import generic
from app_RRHH import models
from app_RRHH.forms import EditarF

# Create your views here.
class HomeView(generic.View):
    title = 'Recursos Humanos'

    def get(self, request, *args, **kwargs):
        activo = models.Empleado.objects.filter(activo=True).count()
        no_activo = models.Empleado.objects.filter(activo=False).count()
        empleado = models.Empleado.objects.all().order_by('id')
        contar = models.Empleado.objects.count()
        context = {
            'title':self.title,
            'activo':activo, 
            'noactivo': no_activo,
            'empleado':empleado,
            'contar':contar,
        }
        return render(request, 'rrhh.html', context)

 
class CreatePersona(generic.CreateView):
    model = models.Empleado
    fields = "__all__"
    
    def get_success_url(self):
        return reverse_lazy('app_RRHH:rrhhhome')


class DetalleView(generic.DetailView):
    model = models.Empleado


class EditarView(generic.UpdateView):
    model = models.Empleado
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy('app_RRHH:rrhhhome')

#Otra forma de Editar un Objeto
class EditView(generic.View):

    def get(self, request, id, *args, **kwargs):
        persona = get_object_or_404(models.Empleado, pk=id)
        form = EditarF(instance=persona)
        context = {
            'title':'Vista de Edit',
            'form':form,
        }
        return render(request, 'edit.html', context)

    def post(self, request,id, *args, **kwargs):
        persona = get_object_or_404(models.Empleado, pk=id)
        if request.method=='POST':
            form = EditarF(request.POST, instance=persona )
            if form.is_valid():
                form.save()
                return redirect('app_RRHH:rrhhhome')

class DeleteViews(generic.DeleteView):
    model = models.Empleado

    def get_success_url(self):
        return reverse_lazy('app_RRHH:rrhhhome')

sap/views.py
from django.shortcuts import render
from django.views import generic


class HomeView(generic.View):
    """Esta es la vista de la pag de inicio"""

    def get(self, request, *args, **Kwargs):
        context = {
            'titulo':'Inicio',
            }
        return render(request, 'index.html', context)

templates/app_RRHH/empleado_confirm_delete.html
{% extends "base.html" %}

{% block contenedor %}
<form action="" method="POST">{% csrf_token %}
    <p>¿Estás seguro de que quieres borrar "{{ object }}"?</p>
    <input type="submit" value="Sí, borrar la Persona" />
</form>
{% endblock contenedor %}

templates/app_RRHH/empleado_detail.html
{% extends "base.html" %}

{% block title %}{{title}}{% endblock title %}

{% block contenedor %}
<div class="contenedor ">
    <h3 border-bottom>Persona: {{ object.nombre }} {{object.apellido}}</h3><br>
    <h3>DNI: {{object.dni}}</h3><br>
    <h3>Sexo: {{object.sexo}}</h3><br>
    <h3>Fecha de Nac: {{object.fec_nac}}</h3><br>
    {% if active %}
    <h3>No es Empleado</h3><br>
    {% else %}
    <h3>Empleado Activo</h3><br>
    <h3>{{object.puesto}}</h3><br>
    <h3>Fecha de Ingreso: {{object.fec_ing}}</h3><br>
    <h3>Edad: {{object.edad_persona}}</h3><br>
    {% endif %}

    <a class="btn btn-primary" href="{% url 'app_RRHH:rrhhhome' %}" >Volver</a>
    <a class="btn btn-primary" href="{% url 'app_RRHH:editar' object.id %}" >Editar</a>
    <a class="btn btn-primary" href="{% url 'app_RRHH:delete' object.id %}" >Eliminar</a>
</div>


{% endblock contenedor %}

templates/app_RRHH/empleado_form.html
{% extends "base.html" %}

{% block contenedor %}
<div class="contenedor ">
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Save">
        <a class="btn btn-primary" href="{% url 'app_RRHH:rrhhhome' %}" >Volver</a>
    </form>
</div>
{% endblock contenedor %}

templates/app_RRHH/empleado_update_form.html
{% extends "base.html" %}

{% block contenedor %}
<div class="contenedor ">
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Save">
        <a class="btn btn-primary" href="{% url 'app_RRHH:rrhhhome' %}" >Volver</a>
    </form>
</div>
{% endblock contenedor %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
<header>
    <div class="header">
        <h2>Sistema de Administracion de Empleados</h2>
    </div>
</header>
<article>
    {% block contenedor %}
    
    {% endblock contenedor %}
</article>
{% include 'footer.html' %}
</body>
</html>

templates/edit.html
{% extends "base.html" %}

{% block contenedor %}
<div class="contenedor ">
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Save">
        <a class="btn btn-primary" href="{% url 'app_RRHH:rrhhhome' %}" >Volver</a>
    </form>
</div>
{% endblock contenedor %}

templates/footer.html
<footer>
    <div class="container">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <div class="col-md-4 d-flex align-items-center">
                <span class="text-muted">&copy; 2022 Proyectos Basic Juan Castro</span>
            </div>
            <a href="#" class="btn btn-outline-primary me-2">Contactanos</a>
            </ul>
        </footer>
    </div>
</footer>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{titulo}}{% endblock title %}

{% block contenedor %}
<h2>Esta es la Pag principal de la practica</h2>

<a class="btn btn-outline-primary" href="{% url 'app_RRHH:rrhhhome' %}">Paguina de RRHH</a>

{% endblock contenedor %}

templates/rrhh.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock title %}

{% block contenedor %}
<td><a class="btn btn-outline-primary" href="{% url 'app_RRHH:create' %}">Crear Persona</a></td>
<br>
<table class="table table-hover">
    <thead>
        <tr class="table-dark">
            <th scope="col">Id</th>
            <th scope="col">Nombre y Apellido</th>
            <th scope="col">Sexo</th>
            <th scope="col">Activo en Planta?</th>
            <th scope="col">Puesto</th>
            <th scope="col">Edad</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for empleados in empleado %}
        <tr>
            <td scope="row">{{ empleado.id }}</td>
            <td>{{ empleados.nombre }} {{ empleado.apellido }}</td>
            <td>{{ empleados.sexo }}</td>
            <td>{{ empleados.activo }}</td>
            <td>{{ empleados.puesto }}</td>
            <td>{{ empleados.edad_persona }}</td>
            <td><a class="btn btn-outline-primary" href="{% url 'app_RRHH:detalle' empleados.id %}">Detalle</a></td>
            <td><a class="btn btn-outline-primary" href="{% url 'app_RRHH:editar' empleados.id %}">Editar</a></td>
            <td><a class="btn btn-outline-primary" href="{% url 'app_RRHH:edit' empleados.id %}">Editar 2</a></td>
            <td><a class="btn btn-outline-primary" href="{% url 'app_RRHH:delete' empleados.id %}">Eliminar</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div class="contenedor">
<h3>hola</h3>
</div>
<a class="btn btn-outline-primary me-2" href="{% url 'home' %}">Volver</a>

<ul class="list-group">
    <li class="list-group-item d-flex justify-content-between align-items-center">
        <h4>Total de empleados de Empleados:</h4>
        <span class="badge bg-primary rounded-pill">{{ contar }}</span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        <h4>Empleados Activos:</h4>
        <span class="badge bg-primary rounded-pill">{{ activo }}</span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        <h4>Empleados No-Activos:</h4>
        <span class="badge bg-primary rounded-pill">{{ noactivo }}</span>
    </li>
</ul>
{% endblock contenedor %}